//===----------------------------------------------------------------------===//
//
// Part of the Trident project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef TRIDENT_CORE_DIALECT_TVMFFI_IR_TVMFFI_TD_
#define TRIDENT_CORE_DIALECT_TVMFFI_IR_TVMFFI_TD_

include "mlir/IR/OpBase.td"

include "trident-core/Dialect/TVMFFI/IR/TVMFFIBase.td"
include "trident-core/Dialect/TVMFFI/IR/TVMFFIAttributes.td"
include "trident-core/Dialect/TVMFFI/IR/TVMFFIOps.td"

#endif // TRIDENT_CORE_DIALECT_TVMFFI_IR_TVMFFI_TD_
