// RUN: libtriton-core-opt %s --torch-to-llvm-pipeline | FileCheck %s
// RUN: libtriton-core-opt %s --torch-to-llvm-pipeline | mlir-translate --mlir-to-llvmir
//
// This test verifies that the TorchToLLVM pipeline correctly lowers
// torch.aten.empty.memory_format (with torch.prim.ListConstruct and
// torch.constant.none) all the way to LLVM dialect, and that a
// tvm_ffi.func wrapper calling the original func.func via func.call
// is also correctly lowered.
//
// The wrapper pattern: tvm_ffi.func calls the lowered
// llvm.func @torch.aten.empty.memory_format, then packs the result
// back into the ret slot.

// TorchExt globals + dispatcher (generated by TorchExtToLLVM):
// CHECK:       llvm.mlir.global internal constant @__libtriton_constant_overload_
// CHECK:       llvm.mlir.global internal constant @"__libtriton_constant_op_aten::empty"
// CHECK:       llvm.func @aoti_torch_call_dispatcher
// CHECK-SAME:    (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32

// -- func.func @torch.aten.empty.memory_format lowered to llvm.func --
// CHECK-LABEL: llvm.func @torch.aten.empty.memory_format() -> !llvm.ptr {
// CHECK:         %[[OPNAME:.*]] = llvm.mlir.addressof @"__libtriton_constant_op_aten::empty"
// CHECK-SAME:      : !llvm.ptr
// Constants may appear in any order.
// CHECK-DAG:     %[[C0:.*]] = llvm.mlir.constant(0 : i64) : i64
// CHECK-DAG:     %[[C6:.*]] = llvm.mlir.constant(6 : i64) : i64
// List construction: torch_new_list_reserve_size(2) then torch_list_push_back × 2.
// CHECK-DAG:     llvm.call @torch_new_list_reserve_size
// CHECK-DAG:     llvm.call @torch_list_push_back
// CHECK-DAG:     llvm.call @torch_list_push_back
// Allocate the dispatcher slot array.
// CHECK:         %[[SLOTS:.*]] = llvm.alloca %[[C6]] x i64 : (i64) -> !llvm.ptr
// Slot 0: list → ptrtoint → store.
// CHECK:         llvm.store {{%.*}}, %[[SLOTS]] : i64, !llvm.ptr
// Slots 1..5 are torch.none → constant 0.
// CHECK:         llvm.getelementptr %[[SLOTS]][1]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// CHECK:         llvm.getelementptr %[[SLOTS]][2]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// CHECK:         llvm.getelementptr %[[SLOTS]][3]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// CHECK:         llvm.getelementptr %[[SLOTS]][4]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// CHECK:         llvm.getelementptr %[[SLOTS]][5]
// CHECK:         llvm.store {{%.*}}, {{%.*}} : i64, !llvm.ptr
// Call dispatcher with (op_name, overload_name, slot_array).
// CHECK:         %[[RET:.*]] = llvm.call @aoti_torch_call_dispatcher(%[[OPNAME]], {{%.*}}, %[[SLOTS]])
// CHECK-SAME:      : (!llvm.ptr, !llvm.ptr, !llvm.ptr) -> i32
// Load the result from slot[0] and convert i64 → !llvm.ptr.
// CHECK-NEXT:    %[[RES_VAL:.*]] = llvm.load %[[SLOTS]] : !llvm.ptr -> i64
// CHECK-NEXT:    %[[ATEN_PTR:.*]] = llvm.inttoptr %[[RES_VAL]] : i64 to !llvm.ptr
// CHECK:         llvm.alloca {{%.*}} x !llvm.ptr : (i64) -> !llvm.ptr
// CHECK:         llvm.call @mLibTritonTensorToTVMFFIObject(%[[ATEN_PTR]],
// CHECK:         %[[RES_PTR:.*]] = llvm.load {{%.*}} : !llvm.ptr -> !llvm.ptr
// CHECK-NEXT:    llvm.return %[[RES_PTR]] : !llvm.ptr
func.func @torch.aten.empty.memory_format() -> !torch.vtensor<[3,4],f64> {
  %int3 = torch.constant.int 3
  %int4 = torch.constant.int 4
  %shape = torch.prim.ListConstruct %int3, %int4 : (!torch.int, !torch.int) -> !torch.list<int>
  %none = torch.constant.none
  %0 = torch.aten.empty.memory_format %shape, %none, %none, %none, %none, %none : !torch.list<int>, !torch.none, !torch.none, !torch.none, !torch.none, !torch.none -> !torch.vtensor<[3,4],f64>
  return %0 : !torch.vtensor<[3,4],f64>
}

// tvm_ffi.func wrapper: calls func.func @torch.aten.empty.memory_format via func.call.
// CHECK-LABEL: llvm.func @__tvm_ffi_empty(
// CHECK-SAME:    %arg0: !llvm.ptr, %[[WRAP_ARGS:.*]]: !llvm.ptr, %arg2: i32, %[[WRAP_RET:.*]]: !llvm.ptr) -> i32 {
// Entry block: call the lowered function (no args to unpack).
// CHECK:         %[[ZERO:.*]] = llvm.mlir.constant(0 : i32) : i32
// CHECK:         %[[TYPE70:.*]] = llvm.mlir.constant(70 : i32) : i32
// CHECK:         %[[UNDEF:.*]] = llvm.mlir.undef : !llvm.struct<(i32, i32, i64)>
// CHECK:         llvm.br
// Body block: call the lowered function.
// CHECK:         %[[CALLEE_RET:.*]] = llvm.call @torch.aten.empty.memory_format()
// CHECK-SAME:      : () -> !llvm.ptr
// Wrap the returned handle into TVMFFIAny:
// CHECK:         %[[WITH_IDX:.*]] = llvm.insertvalue %[[TYPE70]], %[[UNDEF]][0]
// CHECK:         %[[VOBJ:.*]] = llvm.ptrtoint %[[CALLEE_RET]]
// CHECK:         %[[WRAPPED:.*]] = llvm.insertvalue %[[VOBJ]], %[[WITH_IDX]][2]
// CHECK:         llvm.store %[[WRAPPED]], %[[WRAP_RET]]
// CHECK:         llvm.return %[[ZERO]] : i32

tvm_ffi.func @empty() -> !torch.vtensor<[3,4],f64> {
  %0 = func.call @torch.aten.empty.memory_format() : () -> !torch.vtensor<[3,4],f64>
  tvm_ffi.return %0 : !torch.vtensor<[3,4],f64>
}
