#ifndef LIBTRITON_CORE_DIALECT_AOTINDUCTOR_IR_AOTINDUCTORDIALECT_H_
#define LIBTRITON_CORE_DIALECT_AOTINDUCTOR_IR_AOTINDUCTORDIALECT_H_

#include "mlir/IR/Dialect.h"

#include "libtriton-core/Dialect/AOTInductor/IR/AOTInductorDialect.h.inc"

#endif // LIBTRITON_CORE_DIALECT_AOTINDUCTOR_IR_AOTINDUCTORDIALECT_H_
